#### Q1- Arbres avec des erreurs ####

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?s  ?o 
WHERE {
	?s rdfs:comment ?o .
   
    filter ((?o != "N/A") && (?o != "0"))
    filter (regex (?o , "erreur","i"))
    
} 

### Q2- Genre botanique des arbres ###

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT  ?s  ?or
WHERE {
	
    ?s <http://data.lof.com/def/tonto#genreBotanique> ?o
        BIND(LCASE(?o) AS ?or)
   
} order by asc (?or)


### Q3 - Diagnostic des arbres du secteurs "1"

SELECT distinct ?s ?diag ?t ?st
WHERE {
 ?s <http://data.lof.com/def/tonto#noteDiag> ?diag ;
    <http://data.lof.com/def/tonto#defaut> ?d ;
    <http://data.lof.com/def/tonto#trottoir> ?t;
    <http://data.lof.com/def/tonto#secteur> ?st.
    
  Filter ((?t ="oui") && (?st ="1"))
}

### Q4- Arbres les plus fréquentés proche du trottoir avec diagnostic et préconisation

SELECT distinct ?s ?diag ?t ?preco ?fr 
WHERE {
 ?s <http://data.lof.com/def/tonto#noteDiag> ?diag ;
    <http://data.lof.com/def/tonto#defaut> ?d ;
    <http://data.lof.com/def/tonto#trottoir> ?t;
    <http://data.lof.com/def/tonto#travauxPreconisesDiag> ?preco ;
    <http://data.lof.com/def/tonto#frenquentationCible> ?fr.
    
  Filter ((?t ="oui") && (?d ="1") )
  Filter (regex(?fr, "fréquent", "i"))
}

### Q4- Arbres les plus fréquentés proche du trottoir les plus fréquentés par secteur à abattre

SELECT distinct ?s ?diag  ?preco ?fr ?secteur
WHERE {
 ?s <http://data.lof.com/def/tonto#noteDiag> ?diag ;
    <http://data.lof.com/def/tonto#defaut> ?d ;
    <http://data.lof.com/def/tonto#trottoir> ?t;
    <http://data.lof.com/def/tonto#travauxPreconisesDiag> ?preco ;
    <http://data.lof.com/def/tonto#frenquentationCible> ?fr;
    <http://data.lof.com/def/tonto#secteur> ?secteur.
    
  Filter ((?t ="oui") && (?d ="1") )
  Filter (regex(?fr, "fréquent", "i"))
  Filter (regex(?preco, "abat", "i"))
}

## Q5: Arbres avec leur potentiel allergisant supérieur à 4 ##

prefix tonto: <http://data.lof.com/def/tonto#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
select ?s ?a
from <http://data.tree.com>
where {?s tonto:genreBotanique ?g.
 ?g tonto:potentiel_allergisant ?a.
  filter (?a = "4"^^xsd:integer)
  }

## Q6: Arbres ayant un defaut proche du trottoir par secteurs, ainsi que la note du diagnostique et la priorite de renouvellement

PREFIX wgs84_pos:<http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX tr: <http://data.lof.com/def/tonto#>
PREFIX dbo: <http://dbpedia.org/ontology/>

SELECT distinct ?subject  ?code  ?anneeDePlantation ?defaut ?noteDiag ?trottoir ?prioriteRenouvellement ?secteur 

WHERE {
  ?subject rdf:type <http://linkedgeodata.org/ontology/Tree>;
          # wgs84_pos:lat ?lat;
          #  wgs84_pos:long ?long;
           tr:code ?code;
           tr:secteur ?secteur;
    tr:noteDiag ?noteDiag;
    tr:prioriteRenouvellement ?prioriteRenouvellement;
    tr:sousCategorie ?sousCategorie;
    tr:trottoir ?trottoir;
    tr:defaut ?defaut.
   
  FILTER ((?defaut = "1") && (?trottoir = "oui"))
  #Filter(isIRI(?genreBotanique))
}
