### First conversion in RDF of the trees dataset ###
### here dataset X_tree_egc_t1.csv ######

prefix lgdo: <http://linkedgeodata.org/0ontology/> 
prefix dbo: <http://dbpedia.org/ontology/> 
prefix tonto: <http://data.lof.com/def/tonto#>
prefix rlof: <http://data.lof.com/id/tree/>


CONSTRUCT 
{
	?s a <http://linkedgeodata.org/ontology/Tree> ;
	tonto:secteur ?secteur;
	tonto:anneeDePlantation ?adp;
	tonto:anneeRealisationDiagnostic ?ard ;
	tonto:anneeTravauxPreconisesDiag ?atpd ;
	tonto:code ?code ;
	tonto:parent  ?urip. # <http://data.lof.com/id/tree/cat/{?codep}

?urip tonto:location ?addr. 

?s tonto:diametreSouche ?dam ;
	dbo:species ?esp ; # resource dbpedia
	tonto:frenquentationCible ?fqc ;
	tonto:genreBotanique ?grbota ;
	tonto:identifiantPlu ?idplu ;
	tonto:intituleProtectionPlu ?labelplu ;
	tonto:noteDiag ?notediag ;
	tonto:prioriteRenouvellement ?prnvlt ;
	tonto:raisonPlantation ?rpl ;
	rdfs:comment ?comment ;
	tonto:sousCategorie ?souscat ;
	tonto:sousCatDesc ?sdesc ;
	tonto:stadeDeDev ?stdev ;
	tonto:stadeDevDiag ?stdiag ;
	tonto:traitementChenille ?tche;
	tonto:travauxPreconisesDiag ?tpdiag ;
	tonto:trottoir ?trott ;
	tonto:typeImplantationPlu ?tplu;
	tonto:variete ?var ;
	tonto:vigueur ?vig .

}

WHERE {
	
?s a <http://linkedgeodata.org/ontology/Tree> .
OPTIONAL {?s <http://data.lof.com/id/tree/adr-secteur> ?secteur }.
OPTIONAL {?s <http://data.lof.com/id/tree/anneedeplantation> ?adp } .
OPTIONAL {?s <http://data.lof.com/id/tree/anneerealisationdiagnostic> ?ard} .
OPTIONAL {?s <http://data.lof.com/id/tree/anneetravauxpreconisesdiag> ?atpd} . 
OPTIONAL {?s <http://data.lof.com/id/tree/code> ?code} .
OPTIONAL {?s <http://data.lof.com/id/tree/code-parent> ?codep } .
OPTIONAL {?s <http://data.lof.com/id/tree/code-parent-desc> ?addr }. 
OPTIONAL {?s <http://data.lof.com/id/tree/diametrearbreaunmetre> ?dam }.
OPTIONAL{?s <http://data.lof.com/id/tree/espece> ?esp.
 # IF (?espece="N/A", "N/A", BIND(IRI(CONCAT("http://dbpedia.org/resource/", ?esp)) AS ?uridbpedia) )
 } .
OPTIONAL {?s <http://data.lof.com/id/tree/frequentationcible> ?fqc} .
OPTIONAL {?s <http://data.lof.com/id/tree/genre-bota> ?grbota }.
OPTIONAL {?s <http://data.lof.com/id/tree/identifiantplu> ?idplu} .
OPTIONAL {?s <http://data.lof.com/id/tree/intituleprotectionplu> ?labelplu }.
OPTIONAL {?s <http://data.lof.com/id/tree/notediagnostic> ?notediag }.
OPTIONAL {?s <http://data.lof.com/id/tree/prioritederenouvellement> ?prnvlt } .
OPTIONAL {?s <http://data.lof.com/id/tree/raisondeplantation> ?rpl } .
OPTIONAL {?s <http://data.lof.com/id/tree/remarques> ?comment}. 
OPTIONAL {?s <http://data.lof.com/id/tree/sous-categorie> ?souscat}. 
OPTIONAL {?s <http://data.lof.com/id/tree/sous-categorie-desc> ?sdesc}. 
OPTIONAL {?s <http://data.lof.com/id/tree/stadededeveloppement> ?stdev} .
OPTIONAL {?s <http://data.lof.com/id/tree/stadedeveloppementdiag> ?stdiag} .
OPTIONAL {?s <http://data.lof.com/id/tree/traitementchenilles> ?tche}. 
OPTIONAL {?s <http://data.lof.com/id/tree/travauxpreconisesdiag> ?tpdiag}. 
OPTIONAL {?s <http://data.lof.com/id/tree/trottoir> ?trott}. 
OPTIONAL {?s <http://data.lof.com/id/tree/typeimplantationplu> ?tplu}. 
OPTIONAL {?s <http://data.lof.com/id/tree/variete> ?var}. 
OPTIONAL {?s <http://data.lof.com/id/tree/vigueur> ?vig }. 

   BIND(IRI(CONCAT("http://data.lof.com/id/tree/cat/", ?codep))AS ?urip)

}



